CREATE TABLE TB_CLIENTE (
  CD_CLIENTE INT NOT NULL PRIMARY KEY,
  NM_CLIENTE VARCHAR(60) NOT NULL,
  CPF INT NUL,
  DT_NASCIMENTO DATETIME,
  TIPO_CLIENTE VARCHAR(40) NULL
)


CREATE TABLE TB_CONTA (
   NR_CONTA INT NOT NULL PRIMARY KEY,
   CD_CLIENTE INT NOT NULL,
   SALDO NUMERIC(10,2) NOT NULL,
)


