USE exercicio10


CREATE TABLE TB_CLIENTE (
  CD_CLIENTE INT NOT NULL PRIMARY KEY,
  NM_CLIENTE VARCHAR(60) NOT NULL,
  CPF INT NULL,
  DT_INCLUSAO DATETIME NOT NULL
)

INSERT INTO TB_CLIENTE VALUES (1, 'MIKA', 0000, '20100301')
INSERT INTO TB_CLIENTE VALUES (2, 'NANA', 1111, '20100401')
INSERT INTO TB_CLIENTE VALUES (3, 'MARIA', 1111, '20100101')
SELECT * FROM TB_CLIENTE

CREATE TABLE TB_VENDAS (
   CD_VENDA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   DT_VENDA DATETIME NOT NULL,
   CD_CLIENTE INT NOT NULL,
   CD_PRODUTO INT NOT NULL,
   QUANTIDADE INT NOT NULL,
   VALOR_TOTAL NUMERIC(10,2) NOT NULL
)

INSERT INTO TB_VENDAS VALUES ('20100301',  1, 1, 51, 12000)
INSERT INTO TB_VENDAS VALUES ('20100101',  2, 1, 22, 2000)
INSERT INTO TB_VENDAS VALUES ('20100101',  3, 1, 10, 500)
SELECT * FROM TB_VENDAS


CREATE TABLE TB_CLIENTE_ALVO (
  CD_CLIENTE INT NOT NULL PRIMARY KEY,
  NM_CLIENTE VARCHAR(60) NOT NULL,
  CPF INT NULL,
  DT_INCLUSAO DATETIME NOT NULL
)

CREATE TABLE TB_CLIENTE_PARCEIRO (
  CD_CLIENTE INT NOT NULL PRIMARY KEY,
  NM_CLIENTE VARCHAR(60) NOT NULL,
  CPF INT NULL,
  DT_INCLUSAO DATETIME NOT NULL
)

TRUNCATE TABLE TB_CLIENTE_PARCEIRO
TRUNCATE TABLE TB_CLIENTE_ALVO
