
-- 1. Criar uma visão particionada VW_FUNCIONARIOS para as tabelas TB_FUNCIONARIO_SE, TB_FUNCIONARIO_PB, TB_FUNCIONARIO_AL que apresentam funcionários para os estados de SE, PB e AL respectivamente. A estrutura geral das Tabelas de Funcionários é:
/*
	CREATE TABLE TB_FUNCIONARIO (
		MATRICULA INT NOT NULL,
		NM_FUNCIONARIO VARCHAR(40) NOT NULL,
		ESTADO CHAR(2) NOT NULL,
		SALARIO NUMERIC (10,2)
	)

	A Chave primária natural para a tabela Funcionário é MATRICULA
	A Coluna de particionamento é ESTADO.
*/

USE exercicio03

DROP TABLE TB_FUCIONARIO_SE
DROP TABLE TB_FUCIONARIO_PB
DROP TABLE TB_FUCIONARIO_AL

CREATE TABLE TB_FUNCIONARIO_SE (
	MATRICULA INT NOT NULL,
	NM_FUNCIONARIO VARCHAR(40) NOT NULL,
	ESTADO CHAR(2) NOT NULL CHECK (ESTADO = 'SE'),
	SALARIO NUMERIC (10,2)
	PRIMARY KEY (MATRICULA, ESTADO)
)

CREATE TABLE TB_FUNCIONARIO_PB (
	MATRICULA INT NOT NULL,
	NM_FUNCIONARIO VARCHAR(40) NOT NULL,
	ESTADO CHAR(2) NOT NULL CHECK (ESTADO = 'PB'),
	SALARIO NUMERIC (10,2)
	PRIMARY KEY (MATRICULA, ESTADO)
)

CREATE TABLE TB_FUNCIONARIO_AL (
	MATRICULA INT NOT NULL,
	NM_FUNCIONARIO VARCHAR(40) NOT NULL,
	ESTADO CHAR(2) NOT NULL CHECK (ESTADO = 'AL'),
	SALARIO NUMERIC (10,2)
	PRIMARY KEY (MATRICULA, ESTADO)
)

CREATE VIEW VW_FUNCIONARIO 
AS
SELECT * FROM TB_FUNCIONARIO_AL
UNION ALL
SELECT * FROM TB_FUNCIONARIO_PB
UNION ALL
SELECT * FROM TB_FUNCIONARIO_SE

-- DROP VIEW VW_FUNCIONARIO

-- 2. Utilizar a visão para verificar comandos de inclusão e atualização.

INSERT INTO VW_FUNCIONARIO(MATRICULA, NM_FUNCIONARIO, ESTADO, SALARIO) VALUES (1, 'JOSE', 'AL', 1770.55)
INSERT INTO VW_FUNCIONARIO(MATRICULA, NM_FUNCIONARIO, ESTADO, SALARIO) VALUES (2, 'MARIA', 'SE', 17000.00)

SELECT * FROM VW_FUNCIONARIO
SELECT * FROM TB_FUNCIONARIO_SE

UPDATE VW_FUNCIONARIO SET SALARIO = 18000.00 WHERE MATRICULA = 2


