CREATE TABLE TB_PRODUTO (
   COD_PRODUTO NUMBER(4) NOT NULL PRIMARY KEY,
   DESCRICAO VARCHAR2 (50) NOT NULL,
   QTD_ESTOQUE NUMBER(6) NOT NULL
);

insert into tb_produto values (123, 'sabonete', 10);
insert into tb_produto values (171, 'creme', 0);

CREATE TABLE TB_PEDIDO (
    COD_PEDIDO NUMBER(4) NOT NULL PRIMARY KEY,
    DT_PEDIDO DATE NOT NULL,
    COD_CLIENTE NUMBER(4) NOT NULL,
    SITUACAO VARCHAR2 (50) CHECK (SITUACAO IN ('PENDENTE', 'PROCESSADO'))
);

insert into tb_pedido values (115, sysdate, 88, 'PENDENTE'); 
insert into tb_pedido values (138, sysdate, 201, 'PENDENTE'); 
insert into tb_pedido values (217, sysdate, 18, 'PENDENTE'); 

CREATE TABLE TB_ITEM_PEDIDO (
    COD_PEDIDO NUMBER (4) NOT NULL,
    COD_PRODUTO NUMBER(4) NOT NULL,
    QUANTIDADE NUMBER(4) NOT NULL,
    PRIMARY KEY (COD_PEDIDO, COD_PRODUTO)
);

insert into tb_item_pedido values (115, 123, 2); 
insert into tb_item_pedido values (115, 171, 5);
insert into tb_item_pedido values (138, 123, 8);
insert into tb_item_pedido values (217, 123, 4);

CREATE SEQUENCE SQ_FATURAMENTO
START WITH 1
INCREMENT BY 1;

CREATE TABLE TB_FATURAMENTO (
    COD_FATURAMENTO NUMBER(4) NOT NULL PRIMARY KEY,
    DT_FATURAMENTO DATE NOT NULL,
    COD_PEDIDO NUMBER(4) REFERENCES TB_PEDIDO (COD_PEDIDO),
    COD_CLIENTE NUMBER(4) NOT NULL,
    SITUACAO VARCHAR2(50) NULL CHECK (SITUACAO IN ('COMPLETO', 'PARCIAL', 'CANCELADO'))
);

CREATE TABLE TB_ITEM_FATURAMENTO (
   COD_FATURAMENTO NUMBER(4) NOT NULL,
   COD_PRODUTO NUMBER(4) NOT NULL,
   QUANTIDADE NUMBER(4) NOT NULL,
   PRIMARY KEY (COD_FATURAMENTO, COD_PRODUTO)
);

CREATE SEQUENCE SQ_CORTE
START WITH 1
INCREMENT BY 1;

CREATE TABLE TB_CORTE (
   COD_CORTE NUMBER(4) NOT NULL PRIMARY KEY,
   COD_FATURAMENTO NUMBER(4) NOT NULL,
   COD_PEDIDO NUMBER(4) NOT NULL,
   COD_PRODUTO NUMBER(4) NOT NULL,
   QTD_CORTE NUMBER(4) NOT NULL
);



